### PR TITLE
added users high scores

### PR DESCRIPTION
**Pull request by robbobfrh84**
Ok, Sorry to turn this into a Brutalist website! I'm excited to start styling it out, but I'm forcing myself to finish all the back/middle-end work before doing so. 

Now, you will have to `npm run seed reset` the db. I had to change the variable types of the floats. They were strings and the sorting (for ranked users) wouldn't work as string. This type of thing wouldn't be a big deal to work around if the db was already filled with users, but for now, might as well keep it ship-shape. It'll still work without doing so, but the users rankings will be incorrect. 

This addition really makes me wanna play it (without cheating).

Screen Shot 2019-05-30 at 6 42 11 PM
-
Screen Shot 2019-05-30 at 6 42 44 PM

### CODE REVIEW

**Comment by matthewmain** [comment]
It's really coming together though! And you're flying through this--at this point you've got the bulk of the server-side built out, which is amazing. Don't even worry about needing to reseed the db in development, that's what development's for! 

I didn't even think about adding an extended ranking list by individual user, but that will be great to have. Love that. (I was thinking the "view all-time high scores" button would just link to the leaderboard--maybe later we can add another button for that, and another on the leaderboard to quickly jump right over to your own rankings.) Could also be cool to make the high scores part of the user profile public, so you could go to other people's profiles and check out their personal rankings. 

But yeah going to be fun to see the high score/rankings start to fill up when it it's live though. Curious to see where the fewest years for each level will start to flatten out and be competitive.

**Comment by robbobfrh84** [comment]
Ya, If you're willing to add these things to the design, that'd be great! I'm getting close to diving into that so it'd be nice to have it updated!

**Comment by robbobfrh84** [comment]
I think we're about due another meetup soon too! I was thinking it'd prob be a good time to update heroku, just to see if any issues pop up on that end as well.

**Comment by matthewmain** [comment]
Sounds good, I added a card for the design updates [here](https://github.com/matthewmain/kiss_the_sky/projects/1#card-22257243), feel free to add anything else I haven't listed. 

What's your schedule like this summer? Let me know and we'll plan a meetup.

**Pull request merged**
