### PR TITLE
Menu Icon Animation

### PR DESCRIPTION
**Pull request by matthewmain**
menu icon animation

This is ALMOST done, but I got hung up plugging it in to the React. Right now, you can click on the menu icon to run the open animation when the menu fades in, and then you can click on it again to run the close animation when the menu fades out. But if you do anything else that hides the menu, the animation gets out of sync. (E.g., the arrow is still displayed after you click the body to hide the menu.)

So what I _really_ need to do is just run my `toggleMenuIconAnimations()` function whenever your `toggleMenu` function gets called, like this:

Screen Shot 2019-08-10 at 3 39 14 PM

Screen Shot 2019-08-10 at 3 39 41 PM

The problem is, this doesn't recognize the function for some reason and throws an error:

Screen Shot 2019-08-10 at 3 28 30 PM

I think it's related to my needing to define the animation variables and functions on window load in order to grab the UI elements that are defined in `menu.js`. So they're not available yet when `menu.js` runs. 

This is not a priority, but if you ever have a moment and want to look at it, do you know off-hand if there's a way for React to access an outside function that's defined after the window loads? If not, maybe easiest fix is just to declare those added menu elements in `index.html` from the beginning?

### CODE REVIEW

**Comment by robbobfrh84** [comment]
That looks great! Animations are tricky with react. I'll take a look at it though

**Comment by matthewmain** [comment]
Thanks! Just curious if you know of any React quick fix for something like this. Otherwise, I'll dig into moving things over to the html and see if that works.

**Comment by robbobfrh84** [comment]
Is the error drawn when you click it or on initial load? It's odd that it doesn't recognize it because it's a global var though.

**Comment by matthewmain** [comment]
It's when you click

**Comment by matthewmain** [comment]
Okay! So adding an animated icon turned out to be more complicated than I thought, haha. The animation is synced with the dropdown now, but I just manually added click listeners to all of the actions that toggle the dropdown. 



The one thing I couldn't get working was when you click the body to hide the dropdown menu. So I just disabled that functionality [here](https://github.com/matthewmain/kiss_the_sky/pull/120/files#diff-256dceae6197be64c2ec491859566d03R26-R28) and [here](https://github.com/matthewmain/kiss_the_sky/pull/120/files#diff-256dceae6197be64c2ec491859566d03R49-R63). This means, as of now, the dropdown stays until you manually dismiss it by either clicking on the icon/avatar or hit one of the menu links.

Probably won't spend much more time on this little feature, so I think the options for this are: 

1) Use the animated icon as-is and lose the fancy click-on-body-to-hide-dropdown functionality you wrote originally.

2) Use the animated icon and you figure out how to add the fancy click-on-body-to-hide-dropdown functionality back in. 😜

3) Just scrap the animated icon and use what we already have.

What do you think?

**Comment by robbobfrh84** [comment]
Hey I like using the animation and drop the "click-on-body" part. The way I wrote that was bound to have issues because it was targeting nested html elements, so any disruptions to that would break it. So, I like the way you have it!

btw, sorry I went awol recently. I got sucked into a little "I'll-wrap-this-up-today" project that sucked me in over the last week. But, i'm wrapping it up today! 🤪

Are you still in Europe?

**Comment by robbobfrh84** [comment]
👍

**Comment by matthewmain** [comment]
Okay, sounds good, I'll merge it. I'll miss that clickaway action though!

**Pull request merged**
