### PR TITLE
rough draft leaderboard style

### PR DESCRIPTION
**Pull request by robbobfrh84**
Screen Shot 2019-06-22 at 12 45 35 PM
Screen Shot 2019-06-22 at 12 45 44 PM

When I started styling this leaderboard, I realized it'd be a good use-case to bring in the grid system that's built into react-bootstrap.

To check it out, you'll have install the dependency for the front-end, So...
- $`cd webapp/client`
- $`npm install bootstrap react-bootstrap`

With the different greens for each level, you had the expert border match the fill. I first had both the beginner and intermediate match their boarder, like this...

Screen Shot 2019-06-22 at 12 37 26 PM

Screen Shot 2019-06-22 at 12 37 33 PM

But thought that the greens were a little bright so went with having them all fill to the same color as the expert. I kept the code noted out, so it'll be REALLY easy to change that, if you'd like. here's how it stands with this PR...

Screen Shot 2019-06-21 at 5 19 34 PM

I know I've mentioned this before, but the font isn't always the same on sketch. Both some of the letters, and specifically the font-weight. It's always either fatter or skinnier, I couldn't get it right on

. But maybe you know a css way to manipulate it on a finer level? 

... Here's the sketch version.
Screen Shot 2019-06-22 at 10 27 04 AM

...Here's the way it looks in the PR

Screen Shot 2019-06-22 at 10 27 09 AM

So, I know we talked about not worrying about mobile, but after I added the grid, it just broke the leaderboard on it's own so I did a stab at a rough version of the design. Thought you might like something like this to have a way to view that's nice for mobile. 

Screen Shot 2019-06-22 at 12 23 56 PM

And I felt that this first stab was "In the ballpark". So, just let me know if any tinkering small changed you'd like. NO PROB!

### CODE REVIEW

**Comment by matthewmain** [comment]
This is looking great! I'm traveling in Maine right now with pretty limited service so I haven't pulled it down yet, but it's so cool to see it coming together in the screenshots.

I do think we should keep the borderless selected tab labels--generally you want to avoid lighter borders with a color background as a rule of thumb. But I agree that the lighter green background shades aren't great. Can we just make all the selected tab background and unselected tab borders the same darker green color for now, then maybe I'll revisit the different green shades in the next iteration? It may actually turn out to look best with a uniform dark green color for all tab borders/backgrounds like that anyway.

As for the fonts, looks like something is overriding the font family in the css? I think the reason you're not getting it to match up is that something is actually overriding the font family as gil-sans or something instead of dosis. It's totally fine for now though; they're really similar fonts. I'll see if I can pin down where the override is happening when I can get wifi and pull it. 

And if bootstrap is already giving you some responsiveness for mobile, that's great! If the three stacked tabs are taking up too much vertical space on the mobile screen, I can really easily mock up a quick mobile design if you want, something that just compresses the tabs to simple selectors without sub-headings or something. Just let me know.

**Comment by robbobfrh84** [comment]
Ok, so I made the tabs all the same color, but kept the code // noted-out. So it'll be easy to customize if desired. 

Screen Shot 2019-06-24 at 6 21 54 PM

With the font... I realized a couple things.  You were correct and it was getting over-ridden by a parent component. I forgot that could/would happen. So, I re-assigned Dosis, however, it's still not 100% the same... Maybe just the (.) dot in the "0". but still looks a bit different. I'm probably missing some variable with the google font that makes it the same. BUT, when looking into the sketch styles a little more, i discovered  this message...

Screen Shot 2019-06-24 at 6 03 43 PM

Is it possible I'm missing a plug-in or something you might know more about. I'm realizing there is a fine-tuned layer to fonts I'm not quite up to speed on. So, this is a nice little hick-up for my edu!

**Comment by matthewmain** [comment]
Ohhhhh, okay this makes sense about the font confusion now! 

So, first, you must not have actually been seeing Dosis when you viewed the design in Sketch because that font isn't installed on your computer. It's a Google font; you can download it [here](https://fonts.google.com/specimen/Dosis?selection.family=Dosis), then just drop it into your "Fonts" folder and Sketch will find it automatically. Sorry, should have given you a heads-up about that. (Among tons of other things about the design that I just threw at you.)

Aaaand, about the dots in the zeros... 😑. I completely forgot, but way back when I chose Dosis as the main font I really liked it for the game except that the zeros have those weird dots. So, being anal, I replaced all the zeros with capitol letter O's to get rid of the dots, both in the svg text and also with a regex for the dynamic numbers. Which is ridiculous and hacky, I know. So the dots in the zeros are expected with this font. If you feel like getting rid of them you can replace them with `<number>.toString().replace(/0/g,"O")` right before the stats are displayed, but that's definitely not necessary. We can keep the dots in the stats. Maybe they even look cool in that context.

Otherwise, this is looking so good! I think the all-dark green tabs are perfect, what do you think?

**Comment by robbobfrh84** [comment]
lol. Well that "O" did stand out quite a bit. lol, so easy to add the regex function to the display. I'll go ahead and add that. 

I did add that google font to the actual code, but I just couldn't figure out how to get it into my sketch software. No big deal as I have in the code when I'm building.

I think the all green looks great, and I'll add that regex in and we'll be set to add this to the code!

**Comment by matthewmain** [comment]
Sounds good! 💫

**Comment by robbobfrh84** [comment]
Screen Shot 2019-06-27 at 6 25 14 PM

Ok fixed the zeros! I'll merge this now!

**Comment by matthewmain** [comment]
Looking great

**Pull request merged**
