### PR TITLE
Adding raw placeholders and routes

### PR DESCRIPTION
**Pull request by robbobfrh84**
I also created a folder `_DOCS` in the `webapp` folder because I've got a few .md 's now. 
- `Z-INDEX_MAP.md` We're handling quite a bit of `z-index` values and this is just a reference for that.
- `DOCS.md` now has all the pages, apis & routes which are updated within the site now.  

Also, when you're on either the *board* pages, I added a button on the menu to take you back to the game page, "game mode"

Screen Shot 2019-04-25 at 5 18 54 PM

### CODE REVIEW

**Comment by matthewmain** [comment]
I LOVE that you're documenting everything so well. This is looking great. 

And I totally forgot to add a way to return to the current game from the non-game urls! That's a really fundamentally necessary UI component, lol. So this is looking good. From a strictly UI/UX standpoint, we might want to label the action "resume current game" so it's more explicit. Another UI option--for a later iteration--might be to add a little bright, eye-catching "resume current game" button somewhere on the non-game screens, instead of in the menu, so there's never any confusion about how to get back to the game. But dropping this in the menu is perfect for now.

**Comment by matthewmain** [comment]
👍

**Comment by robbobfrh84** [comment]
I was thinking that it would need a little more though. There are a few things I've been pondering how the flow would best work. One, is clicking "off" off the menu to collapse it, which I have not. But, it's not quite cohearent or smoothed out yet. 

I Added your comment above about the "game mode" button to the Project Board in thee `Next Sprint(s) & Ideas` section. So, we can address it later. I'm starting to drop a few things in that column. So feel free to dump and thoughts/ideas there as well. OR, if you think it's gettting to big we can break it out somehow.

**Comment by matthewmain** [comment]
Sounds great!

**Pull request merged**
