### PR TITLE
Updating database structure & add saved_games manifest

### PR DESCRIPTION
**Pull request by robbobfrh84**
Mostly, this PR fixes some security issues and cleans out unneeded fields being passed from both the front and back end. Also, It will restructure how we save user games as well as add the additional fields for UI display (title, date, mode, year/season, etc...)

### CODE REVIEW

**Comment by matthewmain** [comment]
Sorry, just saw this! 👍

**Comment by robbobfrh84** [comment]
Ohhh K. So, I've got the full CRUD for the saved games collection in the database. 
- create a new saved game
- read all games 
- update title of game
- delete game

Screen Shot 2019-05-17 at 1 14 49 PM

I also added a timestamp field for data when saved. It's saved down to the sec. but just MM/DD/YY on the UI. Still needs to be styled, but the backend is complete now. 

Screen Shot 2019-05-15 at 10 10 58 AM


When I started doing this I realized there were some potential security issues. Like, you might be able to easily delete somebody else's game with a simple api request. So, I dig in and figured out how to organize it to be more secure. 
- Also, all the actual games will be saved in one Collection on their own. So, not within the user anymore. This will make it easy to move/change how we save and measure where we're at with space and such. 

I have three users with a combined total of 10 saved games 4.4mb. Pretty good! I was actually thinking how this really isn't that much data compared to sites where users can save photos. The save objects are roughly the same size. 

Screen Shot 2019-05-17 at 1 31 56 PM

**Comment by robbobfrh84** [comment]
I'll go ahead and merge this now. I'm not sure, but you may need to drop the database now and re-seed the manifest and start over... might get some errors if not. 

I added the directions to do that here. https://github.com/matthewmain/kiss_the_sky/blob/master/webapp/_DOCS/DEVELOPMENT.md

**Comment by matthewmain** [comment]
This is really great! Feels like a big hurdle has been crossed getting saves fully working. Looks like we'll even have plenty of storage space for now also, which is nice. And I love that you can edit the saved game titles too. You've been busy! 

All I needed to do to get this version running was install "moment", which threw an error at first. Otherwise, all went fine. I was actually able to run it with the same old database--the old saved games weren't visible in the UI, and I assume the old data is still sitting somewhere, but that's fine. I'll just keep using this db as long as it works, then refer back to your notes on how to clear the db if/when something comes up later. Thanks!

(Looks like I thumbs-up'd this too soon earlier--I'll leave the "work in progress" PRs without review requests alone until you request review from now on.)

**Comment by matthewmain** [comment]
...So I actually hit a snag running this locally. (Not sure why it worked originally--i must have been already running the old database, which accepted the new save data.) But after I restarted with `npm start` everything was wiped, including users, and I hit an error trying to create a new user.

So I went through the process of removing the old database under `mongo` and then reseeding, which looks like it worked:

Screen Shot 2019-05-17 at 7 46 56 PM

But when I restarted everything again (`mongod`/`npm start`), I'm still hitting the same error after I enter a new user name:

Screen Shot 2019-05-17 at 7 28 26 PM

Any idea why `resp` wouldn't exist here? Not sure if it's an issue with the code or with my local database.

**Comment by robbobfrh84** [comment]
Shoot, should have given you a heads up that you'd lose access to your old saveds.

**Comment by robbobfrh84** [comment]
I've had issues with session causing errors. Actually, I've been workin seeding users and ran into this. May have fixed in on the branch I'm currently working on...

BUT, I jumped over to the master and tried to replicate your error. But couldn't get it. My directions in the docs are really bad, just realized that. 

Were you able to drop the DB with the `mongo` cli ?
Screen Shot 2019-05-17 at 7 06 41 PM

That's what I did and then
- $`npm run seed all`
- $`npm start`

If you're still having problems, I might push up the current branch I'm working on just to try and test it there.

**Comment by matthewmain** [comment]
Thanks for checking on master. The directions are good--I was able to drop the drop the kts database in the `mongo` cli, and I checked that it was gone with `show databases`. Since I reseeded, I'm now seeing a new empty kts database:

Screen Shot 2019-05-17 at 8 19 35 PM

I also had to clear up a port conflict before I could `npm start` again, but I don't think that would be relevant?

If you want to push up your current branch whenever it's next convenient, I'll see if I run into the same issue on it. I'll also run through all the steps again in case I missed anything.

**Comment by matthewmain** [comment]
for reference, here's what's in the chrome console after loading home > sign up > enter username:

Screen Shot 2019-05-17 at 8 48 55 PM

**Pull request merged**
