### PR TITLE
added raw leaderboard and winning event

### PR DESCRIPTION
**Pull request by robbobfrh84**
### Raw Leaderboard & Winning Event

Screen Shot 2019-05-24 at 11 51 21 AM

Idk why I thought it was going to be a problem to have the `public` code call the react code. I was able to simply put a callback function within the `public` code. So, i don't have to react(ify) the game control buttons now. 

I just added this little callback function in the `index.js` 

Screen Shot 2019-05-22 at 10 22 03 AM

I also had to add this condition because you'd get a looping error when you moved to a different react page. I think it's because react actually deletes the html code for a page when it changes, and when the flower function tried to add more flowers it threw and error. 

Screen Shot 2019-05-24 at 11 31 50 AM

So, I built a little seed loop to fill the leaderboard, as well as seeded a couple games for the `dev` user. 

Warning: I added a lot on the backend. so you may wanna create a new branch off of master if you've got any data saved there you wanna keep. I've tested it a bit manually, but i'll be curious if you have any problems. But!👇

To get all the new seed data you'll just need to run...

- $`npm run seed reset` (Warning: this will wipe everything locally)

But now you should be able to see the raw undesigned leaderboards as well as when you win a game it'll add it to the leadboard!

Also, if you log into the `dev` user, there's a saved game at 95%. play that and it'll win within a few sec to test!

Or...  you probably already know this, but just running the line `highestRedFlowerPct = 100` in the console will trigger the win, if you wanna test it that way.

I added the new endpoints to the docs, but if you wanna see all the leaderboards just go to this url 

- `http://localhost:3004/api/winner`

### CODE REVIEW

**Comment by matthewmain** [comment]
Nice, looks like you've been resolving a lot of react bugs too. I reset the db with the new save data, and it populates the leaderboard great. 

Couple small bugs I noticed: The year count is off by one, i.e., if you win in year 2, then your leaderboard entry shows 2.XX years, which should be 1.XX years since the start of the game. I noticed this because, when I forced a win in the first year, the leaderboard logged NaN years, but then when I waited till after the first spring it logged 2.03 years. Probably related? Maybe the NaN is coming from a variable not getting a value assigned until after the first year passes? ....Not that anyone would ever win in year 1 anyway, lol.

Screen Shot 2019-05-24 at 3 15 01 PM
Screen Shot 2019-05-24 at 3 25 51 PM

**Comment by robbobfrh84** [comment]
Ohhhh good catch. Ya, a year late in the leaderboard would be pretty annoying after a win. 

The culprit... the dynamic summer time isn't defined until after the. So i just did a condition to set it to 800 if it hasn't been set yet. 

Also, I just added a year to the current year to fix the off year after win. 

Screen Shot 2019-05-24 at 5 49 07 PM
Screen Shot 2019-05-24 at 5 48 50 PM

**Comment by robbobfrh84** [comment]
This bug has a them esong > https://www.youtube.com/watch?v=QWT90HzLF3U

**Comment by matthewmain** [comment]
Ahhhh, that makes sense. I was wondering how you tracked the variable year lengths to calculate the decimals. I should have just hard-coded 800 as the initial suL value instead of leaving it unassigned. Nice fix, you really had to dig into the code. 

`var theBoysOfSummer = road != "empty" && beach != "empty" && currentSeason === "summer" ? "here" : "gone"`

**Comment by robbobfrh84** [comment]
{ skin: "brown", sunglasses: true }

**Pull request merged**
