### PR TITLE
Adding status icons with api calls to signup form

### PR DESCRIPTION
**Pull request by robbobfrh84**
This PR will make it so that when a *NEW* user signs up, s/he will be notified if the username & email is available or not via icons on the right, as well as a loading status icon. Also, basic password validations are added on the front end. 

I looked back at your notes from PR #75 that you made awhile back and tried to match the design a bit better. 
- Maybe you know more about this, or how to fix it, but the font-style on sketch (specifically "Gill sans" Is different in at a few font sizes throughout the form page. 
- Maybe the next we chat we can take a look at what's going on, there is some fine-tuning still needed I'm sure. 

Also, I noticed chrome's auto complete is resisting my font-color changes. So, if you use the auto-complete you'll stay in only black color. However, the icon will still show the state. 

Screen Shot 2019-05-07 at 7 44 51 PM

May-07-2019 19-46-11

I actually coded in a 1 sec delay. because the local database doesn't take enough time to see the loading wheel. Also, I made a card to remind me to remove that delay.

### CODE REVIEW

**Comment by robbobfrh84** [comment]
Oh boy. ya, it was in the css, BUT because I didn't have the `@import url('https://fonts.googleapis.com/css?family=Dosis');
` on the react `.css` so it was *falling* back to `Avenir` on the react side.

I think now after walking through some of the style guide I've got better questions to ask. I have a feeling I both doing it the *hard way* && || the *wrong way*. It's actually really nice to go through these flows like this and have you to help figure out the little confusions.

So here is what I've got now

Screen Shot 2019-05-08 at 10 20 16 AM


This I think looks better. However, the `SIGN UP` button is different. Actually, I had that as `sans-sarif` before...

So... Sign-in with Dosis👆... or `sans-sarif 👇... or *other 👉....

Screen Shot 2019-05-08 at 10 20 24 AM

Either way, I think a meetup to go over the design again with what we've learned worked on so far would be good, and for now, we can limp through what we've got.

**Comment by matthewmain** [comment]
That first screenshot is perfect, exactly like my design. Dosis for all the text, including the button. Looks great! (Btw, are you at 90% zoom in the screenshots or am I crazy?) 

Yeah, let's meet up again. I also have some questions about some basic mongo usage--was wanting to delete some saves in shell but haven't been able to quite work out the query language yet. I'm free this afternoon if you want or pretty much any other weekday.

**Comment by robbobfrh84** [comment]
90% zoom? Those were form the browser. I always do `⌘0` on my chrome to double check I"m at 100%. Or do you mean in sketch?

**Comment by matthewmain** [comment]
i meant chrome, yeah. okay i'm just crazy haha

**Pull request merged**
