### PR TITLE
Myhighscore + Settings + Resume button + KTS Icon

### PR DESCRIPTION
**Pull request by robbobfrh84**
ooookey. There's a bit in this PR. Probably should have broken it up.

So, 

- the rough pass at the design for my high scores is done. 
- I added a selected avatar color options to the setting and updated the email
  - feel free to request any changes to format/writing/etc... 
- I added the resume button and realized, there might be a user flow issue with how we handle the logic. If you wanna play around with it and see if it should behave differently and let me know I can adjust it based on any conditions here.

Also,

- I think the only thing to left to implement for the rough design is the popup boxes to replace the 'alerts'

### CODE REVIEW

**Comment by robbobfrh84** [comment]
Screen Shot 2019-07-29 at 1 37 44 PM
Screen Shot 2019-07-29 at 1 37 52 PM

**Comment by robbobfrh84** [comment]
I've added your most recent updates as well. After we review this, I think I'll deploy this version, and see if you wanna seed some of the high scores/users to test there as well. We can adjust the scores to be easier to beat also, if you'd like.

**Comment by matthewmain** [comment]
Looks great! The avatar options are perfect. And yeah, feel free to seed test users.

**Comment by matthewmain** [comment]
Btw, I'm cool with the MVP just using the current browser dialogue boxes for alerts, if you want to just leave that out for now and move on?

**Pull request merged**
